-- ============================================================
--  Esquema consolidado — Sistema de Evaluacion de Riesgo ISO/IEC 27002
--  Un solo archivo: crea la base, todas las tablas (con las columnas
--  de objetivo/peso/CID que usa el codigo PHP) y los datos semilla
--  (7 dominios, 15 controles con peso y relacion CID, 75 preguntas).
--
--  Import UNICO necesario: este archivo. Las migraciones sueltas que
--  existian antes en database/ quedaron archivadas en database/archive/
--  porque su contenido ya esta incorporado aqui.
-- ============================================================

CREATE DATABASE IF NOT EXISTS consultora_iso27002
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE consultora_iso27002;

-- organization_id: NULL para el personal de la consultora (admin y auditores
-- asignados manualmente, que pueden trabajar cualquier organizacion). Se
-- llena solo cuando el usuario se autoregistra desde /register, y lo limita
-- a ver y gestionar unicamente esa organizacion (ver App\Core\Middleware::
-- ownsOrganization).
CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(160) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('admin', 'auditor', 'viewer') NOT NULL DEFAULT 'auditor',
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    organization_id INT UNSIGNED NULL,
    last_login_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE organizations (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(180) NOT NULL,
    address VARCHAR(255) NULL,
    email VARCHAR(160) NULL,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_organizations_name (name)
) ENGINE=InnoDB;

ALTER TABLE users
    ADD CONSTRAINT fk_users_organization FOREIGN KEY (organization_id) REFERENCES organizations(id);

CREATE TABLE areas (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    organization_id INT UNSIGNED NOT NULL,
    name VARCHAR(160) NOT NULL,
    description TEXT NULL,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_areas_organization_name (organization_id, name),
    CONSTRAINT fk_areas_organization FOREIGN KEY (organization_id) REFERENCES organizations(id)
) ENGINE=InnoDB;

CREATE TABLE iso_domains (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(180) NOT NULL,
    description TEXT NULL,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- iso_controls incluye desde el inicio objective/weight/CID: antes estas
-- columnas se agregaban con una migracion aparte (migration_fase3_4.sql)
-- que ademas tenia un bug: dejaba sin crear la columna "weight", pero el
-- codigo PHP (IsoControlController/IsoControl model) y el script de pesos
-- ya la necesitaban desde el primer INSERT/UPDATE.
CREATE TABLE iso_controls (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    domain_id INT UNSIGNED NULL,
    code VARCHAR(30) NOT NULL UNIQUE,
    title VARCHAR(220) NOT NULL,
    description TEXT NULL,
    objective TEXT NULL,
    weight DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    confidentiality TINYINT UNSIGNED NOT NULL DEFAULT 1,
    integrity TINYINT UNSIGNED NOT NULL DEFAULT 1,
    availability TINYINT UNSIGNED NOT NULL DEFAULT 1,
    iso_reference VARCHAR(60) NULL,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_iso_controls_domain FOREIGN KEY (domain_id) REFERENCES iso_domains(id)
) ENGINE=InnoDB;

CREATE TABLE questions (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    control_id INT UNSIGNED NOT NULL,
    question TEXT NOT NULL,
    weight DECIMAL(5,2) NOT NULL DEFAULT 1.00,
    status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_questions_control FOREIGN KEY (control_id) REFERENCES iso_controls(id)
) ENGINE=InnoDB;

-- Explica, por pregunta, que representa cada nivel de madurez (0-5) al
-- responderla. Se siembra con el texto oficial de la escala del enunciado
-- EIF402 (identico para las 75 preguntas); el equipo puede refinarlo por
-- pregunta despues desde el modulo de Preguntas.
CREATE TABLE question_maturity_scale (
    id          INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    question_id INT UNSIGNED NOT NULL,
    level       TINYINT UNSIGNED NOT NULL,
    description TEXT NOT NULL,
    UNIQUE KEY uq_qms (question_id, level),
    CONSTRAINT fk_qms_question FOREIGN KEY (question_id) REFERENCES questions(id)
) ENGINE=InnoDB;

CREATE TABLE audits (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    organization_id INT UNSIGNED NOT NULL,
    area_id INT UNSIGNED NOT NULL,
    auditor_user_id INT UNSIGNED NOT NULL,
    dba_name VARCHAR(160) NULL,
    name VARCHAR(200) NOT NULL,
    status ENUM('draft', 'in_progress', 'closed', 'cancelled') NOT NULL DEFAULT 'draft',
    start_date DATE NOT NULL,
    end_date DATE NULL,
    maturity_score DECIMAL(5,2) NULL,
    risk_score DECIMAL(5,2) NULL,
    risk_c DECIMAL(5,2) NULL,
    risk_i DECIMAL(5,2) NULL,
    risk_d DECIMAL(5,2) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_audits_organization FOREIGN KEY (organization_id) REFERENCES organizations(id),
    CONSTRAINT fk_audits_area FOREIGN KEY (area_id) REFERENCES areas(id),
    CONSTRAINT fk_audits_auditor_user FOREIGN KEY (auditor_user_id) REFERENCES users(id)
) ENGINE=InnoDB;

CREATE TABLE responses (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    audit_id INT UNSIGNED NOT NULL,
    question_id INT UNSIGNED NOT NULL,
    answer ENUM('yes','no','na') NULL,
    maturity_level TINYINT UNSIGNED NULL,
    justification TEXT NULL,
    recommendation TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_responses_audit FOREIGN KEY (audit_id) REFERENCES audits(id),
    CONSTRAINT fk_responses_question FOREIGN KEY (question_id) REFERENCES questions(id),
    CONSTRAINT uq_responses_audit_question UNIQUE (audit_id, question_id)
) ENGINE=InnoDB;

CREATE TABLE audit_control_maturity (
    id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    audit_id     INT UNSIGNED NOT NULL,
    control_id   INT UNSIGNED NOT NULL,
    maturity_level TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_acm (audit_id, control_id),
    CONSTRAINT fk_acm_audit   FOREIGN KEY (audit_id)   REFERENCES audits(id),
    CONSTRAINT fk_acm_control FOREIGN KEY (control_id) REFERENCES iso_controls(id)
) ENGINE=InnoDB;

CREATE TABLE evidences (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    response_id INT UNSIGNED NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    size_bytes INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_evidences_response FOREIGN KEY (response_id) REFERENCES responses(id)
) ENGINE=InnoDB;

CREATE TABLE recommendations (
    id           INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    audit_id     INT UNSIGNED NOT NULL,
    control_id   INT UNSIGNED NOT NULL,
    description  TEXT NOT NULL,
    responsible  VARCHAR(160) NULL,
    due_date     DATE NULL,
    status       ENUM('pending','in_progress','done') NOT NULL DEFAULT 'pending',
    notes        TEXT NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_rec_audit   FOREIGN KEY (audit_id)   REFERENCES audits(id),
    CONSTRAINT fk_rec_control FOREIGN KEY (control_id) REFERENCES iso_controls(id)
) ENGINE=InnoDB;

INSERT INTO users (name, email, password, role, status)
VALUES (
    'Administrador',
    'admin@datasolutionscr.net',
    'BOOTSTRAP_ADMIN_PASSWORD',
    'admin',
    'active'
);

-- ------------------------------------------------------------
-- Datos semilla: 7 dominios
-- ------------------------------------------------------------
INSERT INTO iso_domains (code, name, description, status) VALUES
('D1', 'Gobierno y políticas', 'Políticas y gobierno de seguridad de la información', 'active'),
('D2', 'Gestión de activos', 'Inventario y clasificación de activos', 'active'),
('D3', 'Control de accesos', 'Control y gestión de accesos y privilegios', 'active'),
('D4', 'Criptografía y comunicaciones', 'Protección de la información en tránsito y en reposo', 'active'),
('D5', 'Operaciones y continuidad', 'Gestión de operaciones, continuidad y copia de seguridad', 'active'),
('D6', 'Seguridad física y ambiental', 'Protección física de las instalaciones y equipos', 'active'),
('D7', 'Cumplimiento y gestión de riesgos', 'Auditoría, cumplimiento normativo y gestión de riesgos', 'active');

-- ------------------------------------------------------------
-- Datos semilla: 15 controles, con peso, relacion CID y
-- referencia ISO/IEC 27002:2022 (columna "Ref. ISO" del documento
-- de analisis del equipo, seccion 4.2) ya definitivos.
-- NOTA: el campo "objective" (objetivo del control) queda
-- pendiente de redactar por el equipo — no se inventa contenido
-- academico aqui; se puede completar luego desde Controles > Editar.
-- ------------------------------------------------------------
INSERT INTO iso_controls (domain_id, code, title, description, weight, confidentiality, integrity, availability, iso_reference, status) VALUES
((SELECT id FROM iso_domains WHERE code='D1'), 'C1', 'Política de seguridad', 'Existencia y comunicación de la política de seguridad', 1.50, 1, 1, 1, '5.1', 'active'),
((SELECT id FROM iso_domains WHERE code='D1'), 'C2', 'Organización de la seguridad', 'Roles y responsabilidades de seguridad', 1.00, 1, 1, 0, '5.2 / 5.3', 'active'),
((SELECT id FROM iso_domains WHERE code='D2'), 'C3', 'Inventario de activos', 'Identificación y clasificación de activos', 1.00, 1, 1, 0, '5.9', 'active'),
((SELECT id FROM iso_domains WHERE code='D2'), 'C4', 'Propiedad de activos', 'Responsables y propietarios de activos', 1.00, 1, 1, 0, '5.10', 'active'),
((SELECT id FROM iso_domains WHERE code='D3'), 'C5', 'Control de accesos lógicos', 'Gestión de cuentas y accesos', 2.00, 1, 1, 1, '8.2 / 8.3', 'active'),
((SELECT id FROM iso_domains WHERE code='D3'), 'C6', 'Gestión de privilegios', 'Asignación y revisión de privilegios', 2.00, 1, 1, 1, '8.2', 'active'),
((SELECT id FROM iso_domains WHERE code='D4'), 'C7', 'Criptografía', 'Uso adecuado de controles criptográficos', 1.50, 1, 0, 0, '8.24', 'active'),
((SELECT id FROM iso_domains WHERE code='D4'), 'C8', 'Seguridad en comunicaciones', 'Protección de información en tránsito', 1.00, 1, 1, 0, '8.20 / 8.21', 'active'),
((SELECT id FROM iso_domains WHERE code='D5'), 'C9', 'Seguridad en operaciones', 'Procedimientos operativos y seguridad', 1.50, 0, 1, 1, '8.9 / 8.32', 'active'),
((SELECT id FROM iso_domains WHERE code='D5'), 'C10', 'Gestión de incidentes', 'Detección, respuesta y registro de incidentes', 1.50, 0, 1, 1, '5.24 / 5.26', 'active'),
((SELECT id FROM iso_domains WHERE code='D6'), 'C11', 'Control físico', 'Protección de accesos físicos y equipos', 1.00, 1, 0, 1, '7.2 / 7.4', 'active'),
((SELECT id FROM iso_domains WHERE code='D6'), 'C12', 'Protección ambiental', 'Medidas ambientales y de infraestructura', 1.00, 0, 0, 1, '7.5 / 7.8', 'active'),
((SELECT id FROM iso_domains WHERE code='D7'), 'C13', 'Evaluación de riesgos', 'Procesos de identificación y tratamiento de riesgos', 1.50, 1, 1, 1, '6.1 / 8.8', 'active'),
((SELECT id FROM iso_domains WHERE code='D7'), 'C14', 'Cumplimiento legal', 'Cumplimiento de requisitos legales y contractuales', 1.00, 1, 0, 0, '5.31 / 5.32', 'active'),
((SELECT id FROM iso_domains WHERE code='D7'), 'C15', 'Auditoría y revisión', 'Revisión periódica y auditorías internas', 1.00, 1, 1, 1, '5.35 / 5.36', 'active');

-- ------------------------------------------------------------
-- Datos semilla: 75 preguntas (5 por control)
-- ------------------------------------------------------------
INSERT INTO questions (control_id, question, weight, status) VALUES
((SELECT id FROM iso_controls WHERE code='C1'), '¿Existe una política de seguridad documentada y aprobada por la dirección?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C1'), '¿La política de seguridad se comunica a todos los empleados y terceros relevantes?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C1'), '¿La política se revisa periódicamente y se actualiza según cambios organizacionales?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C1'), '¿Se dispone de indicadores o métricas para verificar el cumplimiento de la política?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C1'), '¿La política define el alcance y los objetivos de seguridad de la información?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C2'), '¿Están definidas las responsabilidades y roles de seguridad en la organización?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C2'), '¿Existe un comité o responsable asignado para gobernanza de seguridad?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C2'), '¿Se realizan actividades de concienciación y formación en seguridad?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C2'), '¿Se gestionan acuerdos y responsabilidades con terceros?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C2'), '¿Se establecen criterios para aceptación y gestión de riesgos?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C3'), '¿Existe un inventario actualizado de activos de información?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C3'), '¿Los activos están clasificados según su criticidad y sensibilidad?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C3'), '¿Se registran los propietarios y custodios de cada activo?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C3'), '¿Se realizan revisiones periódicas del inventario de activos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C3'), '¿Hay controles para el manejo y etiquetado de soportes y activos?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C4'), '¿Están asignados claramente los propietarios de activos y sus responsabilidades?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C4'), '¿Se definen procesos para la adquisición y baja de activos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C4'), '¿Se controla el acceso físico y lógico a los activos críticos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C4'), '¿Existe un registro de ubicación para activos móviles y portátiles?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C4'), '¿Se realizan copias de respaldo de activos críticos según política?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C5'), '¿Se aplican controles de acceso basados en el principio de menor privilegio?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C5'), '¿Existen procedimientos para la gestión del ciclo de vida de cuentas de usuario?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C5'), '¿Se auditan y revisan los accesos periódicamente?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C5'), '¿Se utilizan mecanismos de autenticación adecuados (2FA, contraseñas fuertes)?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C5'), '¿Se gestionan cuentas de servicio y accesos compartidos de forma segura?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C6'), '¿Se revisan y actualizan privilegios cuando cambian roles o personas?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C6'), '¿Hay procedimientos para la aprobación y registro de privilegios elevados?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C6'), '¿Se monitorizan actividades de cuentas con privilegios altos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C6'), '¿Se aplican controles para prevenir el abuso de privilegios?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C6'), '¿Se separan funciones críticas para evitar conflictos de interés?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C7'), '¿Se utilizan algoritmos y parámetros criptográficos aprobados por la organización?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C7'), '¿Se gestionan y protegen adecuadamente las claves criptográficas?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C7'), '¿Se aplican criptografía para proteger datos sensibles en reposo cuando es necesario?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C7'), '¿Se protege la información confidencial en backups mediante criptografía cuando corresponde?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C7'), '¿Se revisan periodicamente las políticas de uso de criptografía?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C8'), '¿Se cifran o aseguran canales de comunicación que transportan información sensible?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C8'), '¿Se usan VPNs o canales seguros para accesos remotos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C8'), '¿Se controlan y registran las conexiones entrantes y salientes críticas?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C8'), '¿Se aplican políticas para uso seguro de correo y transferencias de archivos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C8'), '¿Se gestionan acuerdos con proveedores de servicios de comunicaciones?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C9'), '¿Existen procedimientos operativos documentados y conocidos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C9'), '¿Se aplican controles para cambios en producción (change management)?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C9'), '¿Se realiza monitoreo y registro de eventos operativos relevantes?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C9'), '¿Se gestionan parches y vulnerabilidades en sistemas críticos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C9'), '¿Se realizan revisiones de configuración y seguridad periódicas?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C10'), '¿Existe un proceso formal para la gestión de incidentes de seguridad?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C10'), '¿Se registran y clasifican los incidentes y se da seguimiento?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C10'), '¿Se realizan pruebas y ejercicios de respuesta a incidentes?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C10'), '¿Se dispone de canales definidos para reportar incidentes?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C10'), '¿Se retroalimenta la organización con lecciones aprendidas tras incidentes?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C11'), '¿Se controlan accesos físicos a instalaciones críticas?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C11'), '¿Existen medidas de protección para equipos y servidores?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C11'), '¿Se gestionan visitantes y accesos temporales de forma segura?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C11'), '¿Se realizan inspecciones y mantenimiento de controles físicos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C11'), '¿Hay controles de redundancia y recuperación física para equipos críticos?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C12'), '¿Se adoptan medidas ambientales para proteger activos (temperatura, humedad)?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C12'), '¿Se dispone de sistemas contra incendios y detección adecuada?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C12'), '¿Se protege la infraestructura eléctrica y suministros críticos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C12'), '¿Se realizan evaluaciones de riesgo físico y ambiental periódicas?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C12'), '¿Hay planes de contingencia ante fallas ambientales?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C13'), '¿Se realiza identificación y evaluación periódica de riesgos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C13'), '¿Se documentan los tratamientos y planes de mitigación de riesgos?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C13'), '¿Se priorizan riesgos según impacto y probabilidad?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C13'), '¿Se revisan los riesgos tras cambios significativos en la organización?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C13'), '¿Se comunican los riesgos a la alta dirección y partes interesadas?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C14'), '¿Se identifican requisitos legales y regulatorios aplicables?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C14'), '¿Se gestionan los contratos y obligaciones con proveedores en materia de seguridad?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C14'), '¿Se mantiene evidencia de cumplimiento y registros necesarios?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C14'), '¿Se realizan auditorías para verificar cumplimiento legal?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C14'), '¿Se evalúa impacto de cambios regulatorios en la organización?', 1.00, 'active'),

((SELECT id FROM iso_controls WHERE code='C15'), '¿Se realizan auditorías internas periódicas de seguridad de la información?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C15'), '¿Se documentan hallazgos y se hace seguimiento a las acciones correctivas?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C15'), '¿Se revisan los controles y resultados de auditoría con la dirección?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C15'), '¿Se mantienen registros de auditoría y evidencias suficientes?', 1.00, 'active'),
((SELECT id FROM iso_controls WHERE code='C15'), '¿Se evalúa la eficacia de las acciones tomadas tras auditorías?', 1.00, 'active');

-- ------------------------------------------------------------
-- Datos semilla: escala de madurez 0-5 explicada por pregunta.
-- Cada pregunta tiene su propia interpretacion de que representa
-- cada nivel oficial (0-5, ver enunciado EIF402) para su tema
-- especifico. Redactado con base en practicas documentadas de
-- auditoria/gestion de seguridad (revision de accesos ISO/IEC
-- 27002 8.2, controles ITGC de backup/RTO-RPO, madurez de gestion
-- de llaves criptograficas, modelos de madurez de respuesta a
-- incidentes, controles fisicos/ambientales ITGC-HITRUST, ciclo
-- PDCA de ISO/IEC 27005) — NO es texto inventado sin fundamento;
-- ver database/seed_maturity_scale.php para el detalle y fuentes.
-- ------------------------------------------------------------
INSERT INTO question_maturity_scale (question_id, level, description) VALUES
(1, 0, 'No existe ninguna política de seguridad, ni siquiera en borrador.'),
(1, 1, 'Hay lineamientos de seguridad informales (correos, acuerdos verbales), sin un documento formal.'),
(1, 2, 'Existe un borrador de política, pero no ha sido aprobado formalmente por la dirección.'),
(1, 3, 'La política está documentada, aprobada por la dirección y se aplica en la mayoría de los procesos.'),
(1, 4, 'La política aprobada se supervisa periódicamente y hay evidencia de su cumplimiento (actas, firmas, revisiones).'),
(1, 5, 'La política se revisa y mejora de forma continua, con indicadores de cumplimiento medidos en el tiempo.'),
(2, 0, 'La política de seguridad no se comunica a nadie.'),
(2, 1, 'Se comunica de manera ocasional o solo a algunos empleados, sin un canal definido.'),
(2, 2, 'Existe un mecanismo de comunicación, pero no llega de forma consistente a todo el personal ni a terceros.'),
(2, 3, 'La política se comunica formalmente a todo el personal y terceros relevantes al ingresar o en capacitaciones periódicas.'),
(2, 4, 'La comunicación se supervisa (acuses de recibido, registros de asistencia) y se verifica su alcance real.'),
(2, 5, 'Se mide la efectividad de la comunicación (encuestas, evaluaciones) y el proceso de difusión mejora continuamente.'),
(3, 0, 'La política nunca se ha revisado desde que fue creada.'),
(3, 1, 'Se revisa de forma esporádica, sin calendario ni criterio definido.'),
(3, 2, 'Existe intención de revisión periódica, pero no se documenta ni se cumple de forma consistente.'),
(3, 3, 'Se revisa con una periodicidad definida (por ejemplo, anual) y se actualiza cuando hay cambios relevantes.'),
(3, 4, 'Las revisiones están documentadas y supervisadas, y quedan evidencias formales de cada actualización.'),
(3, 5, 'El proceso de revisión está integrado en un ciclo de mejora continua, con indicadores de cuándo y por qué se actualiza.'),
(4, 0, 'No existen indicadores de ningún tipo para verificar el cumplimiento de la política.'),
(4, 1, 'Se mencionan métricas de forma informal, sin registrarlas ni darles seguimiento.'),
(4, 2, 'Existen algunos indicadores definidos, pero no se recolectan de forma consistente.'),
(4, 3, 'Hay indicadores documentados que se recolectan periódicamente para la mayoría de los procesos.'),
(4, 4, 'Los indicadores se supervisan activamente y sirven de base para reportes formales de cumplimiento.'),
(4, 5, 'Los indicadores alimentan un proceso de mejora continua, con metas y revisión de tendencias en el tiempo.'),
(5, 0, 'La política, si existe, no menciona alcance ni objetivos de seguridad.'),
(5, 1, 'El alcance o los objetivos se mencionan de forma vaga o solo verbalmente.'),
(5, 2, 'Existe una definición parcial de alcance/objetivos, incompleta o desactualizada.'),
(5, 3, 'La política define claramente su alcance y objetivos, y son conocidos por la organización.'),
(5, 4, 'El alcance y los objetivos se revisan y validan periódicamente, con evidencia de dicha revisión.'),
(5, 5, 'El alcance y los objetivos se ajustan de forma continua según el contexto de riesgo, con mejora documentada.'),
(6, 0, 'No hay ninguna asignación de responsabilidades o roles de seguridad en la organización.'),
(6, 1, 'Algunas personas asumen responsabilidades de seguridad de manera informal, sin nombramiento oficial.'),
(6, 2, 'Existen roles definidos en algún documento, pero no se aplican de forma consistente en la práctica.'),
(6, 3, 'Los roles y responsabilidades de seguridad están documentados, asignados y comunicados a la mayoría de la organización.'),
(6, 4, 'Las responsabilidades se supervisan periódicamente y hay evidencia de que se cumplen (reportes, bitácoras).'),
(6, 5, 'Los roles se revisan y ajustan continuamente según la evolución de la organización, con métricas de desempeño.'),
(7, 0, 'No existe ningún comité ni responsable asignado para la gobernanza de seguridad.'),
(7, 1, 'Alguien atiende temas de seguridad de forma ocasional, sin mandato ni reuniones formales.'),
(7, 2, 'Existe un responsable nombrado, pero sin comité formal ni reuniones periódicas documentadas.'),
(7, 3, 'Hay un comité o responsable formal de gobernanza que se reúne con una periodicidad definida.'),
(7, 4, 'El comité supervisa activamente los temas de seguridad y deja actas o minutas como evidencia.'),
(7, 5, 'La gobernanza de seguridad se mide y mejora continuamente, con indicadores de gestión reportados a la alta dirección.'),
(8, 0, 'No se realiza ninguna actividad de concienciación o formación en seguridad.'),
(8, 1, 'Hay charlas o correos aislados sobre seguridad, sin plan ni periodicidad.'),
(8, 2, 'Existe un plan de concienciación, pero se ejecuta de forma parcial o incompleta.'),
(8, 3, 'Se imparte formación en seguridad de forma periódica a la mayoría del personal, con registro de asistencia.'),
(8, 4, 'La formación se supervisa y se evalúa (pruebas, encuestas) con evidencia documentada de resultados.'),
(8, 5, 'El programa de concienciación se mide y mejora continuamente según los resultados obtenidos (ej. simulacros de phishing).'),
(9, 0, 'No se gestionan acuerdos ni responsabilidades de seguridad con terceros.'),
(9, 1, 'Se mencionan responsabilidades de seguridad a terceros de forma verbal, sin contrato específico.'),
(9, 2, 'Existen cláusulas de seguridad en algunos contratos, pero no de forma sistemática.'),
(9, 3, 'Los acuerdos con terceros incluyen cláusulas de seguridad documentadas para la mayoría de los proveedores relevantes.'),
(9, 4, 'El cumplimiento de las cláusulas se supervisa periódicamente, con evidencia de revisiones o auditorías a terceros.'),
(9, 5, 'La gestión de terceros se mide y mejora continuamente, con criterios de riesgo actualizados por proveedor.'),
(10, 0, 'No existen criterios definidos para aceptación o gestión de riesgos.'),
(10, 1, 'Los riesgos se aceptan o rechazan de forma informal, según criterio individual.'),
(10, 2, 'Existen criterios de aceptación de riesgo esbozados, pero no se aplican de forma consistente.'),
(10, 3, 'Hay criterios documentados de aceptación de riesgo que se aplican en la mayoría de las decisiones.'),
(10, 4, 'Los criterios se supervisan y las decisiones de riesgo quedan formalmente evidenciadas y aprobadas.'),
(10, 5, 'Los criterios de aceptación de riesgo se revisan y ajustan continuamente según el apetito de riesgo de la organización.'),
(11, 0, 'No existe ningún inventario de activos de información.'),
(11, 1, 'Hay listas parciales o informales de activos, hechas de manera ocasional.'),
(11, 2, 'Existe un inventario, pero está incompleto o desactualizado respecto a los activos reales.'),
(11, 3, 'El inventario está documentado, actualizado y cubre la mayoría de los activos de información relevantes.'),
(11, 4, 'El inventario se supervisa y actualiza periódicamente, con evidencia de las revisiones realizadas.'),
(11, 5, 'El inventario se mantiene y mejora de forma continua, integrado a procesos automatizados de descubrimiento de activos.'),
(12, 0, 'Los activos no tienen ningún tipo de clasificación por criticidad o sensibilidad.'),
(12, 1, 'Algunos activos se clasifican de manera informal, sin criterio documentado.'),
(12, 2, 'Existe un esquema de clasificación, pero se aplica de forma inconsistente a los activos.'),
(12, 3, 'La mayoría de los activos están clasificados según criticidad/sensibilidad, siguiendo un esquema documentado.'),
(12, 4, 'La clasificación se supervisa periódicamente y hay evidencia de revisiones para mantenerla vigente.'),
(12, 5, 'El esquema de clasificación se mide y mejora continuamente, ajustándose a nuevos tipos de activos o riesgos.'),
(13, 0, 'No se registran propietarios ni custodios de los activos.'),
(13, 1, 'Se conoce informalmente quién usa cada activo, pero no está documentado.'),
(13, 2, 'Existen propietarios asignados para algunos activos, de forma incompleta.'),
(13, 3, 'La mayoría de los activos tienen propietario y custodio formalmente documentados.'),
(13, 4, 'La asignación de propietarios se supervisa y se actualiza con evidencia cuando hay cambios de personal.'),
(13, 5, 'La gestión de propietarios/custodios se revisa y mejora continuamente como parte del ciclo de vida del activo.'),
(14, 0, 'El inventario de activos nunca se revisa.'),
(14, 1, 'Se revisa de forma esporádica, sin calendario definido.'),
(14, 2, 'Existe intención de revisión periódica, pero no se cumple de forma consistente.'),
(14, 3, 'El inventario se revisa con una periodicidad definida y documentada.'),
(14, 4, 'Las revisiones se supervisan activamente y quedan evidencias formales de cada ciclo.'),
(14, 5, 'El proceso de revisión está integrado en un ciclo de mejora continua, con métricas de exactitud del inventario.'),
(15, 0, 'No existe ningún control para el manejo o etiquetado de soportes y activos.'),
(15, 1, 'Algunos soportes se etiquetan de manera informal, sin criterio uniforme.'),
(15, 2, 'Existen lineamientos de etiquetado/manejo, pero se aplican de forma parcial.'),
(15, 3, 'Los soportes y activos se etiquetan y manejan siguiendo procedimientos documentados en la mayoría de los casos.'),
(15, 4, 'El cumplimiento del etiquetado/manejo se supervisa periódicamente con evidencia de verificación.'),
(15, 5, 'Los controles de manejo y etiquetado se revisan y mejoran continuamente según la experiencia operativa.'),
(16, 0, 'No hay propietarios asignados a los activos ni responsabilidades definidas sobre ellos.'),
(16, 1, 'Se asume informalmente quién es responsable de un activo, sin asignación documentada.'),
(16, 2, 'Existen propietarios asignados para algunos activos, de forma incompleta o desactualizada.'),
(16, 3, 'Los propietarios de activos y sus responsabilidades están claramente documentados para la mayoría de los casos.'),
(16, 4, 'La asignación de propietarios se supervisa y se evidencia su cumplimiento (ej. firmas de aceptación).'),
(16, 5, 'La gestión de propietarios se revisa y mejora continuamente, integrada al ciclo de vida completo del activo.'),
(17, 0, 'No existe ningún proceso para la adquisición o baja de activos.'),
(17, 1, 'La adquisición o baja de activos se realiza de manera ad hoc, sin procedimiento.'),
(17, 2, 'Existe un procedimiento esbozado, pero no se sigue de forma consistente.'),
(17, 3, 'Hay un proceso documentado de adquisición y baja de activos que se aplica en la mayoría de los casos.'),
(17, 4, 'El proceso se supervisa y cada adquisición/baja queda registrada como evidencia.'),
(17, 5, 'El proceso de adquisición y baja se mide y mejora continuamente, integrado a la gestión de inventario.'),
(18, 0, 'No hay ningún control de acceso físico ni lógico sobre los activos críticos.'),
(18, 1, 'Existen controles básicos e informales (ej. una llave compartida), sin política definida.'),
(18, 2, 'Hay controles de acceso definidos, pero se aplican de forma inconsistente entre activos críticos.'),
(18, 3, 'El acceso físico y lógico a los activos críticos está controlado siguiendo procedimientos documentados.'),
(18, 4, 'Los controles de acceso se supervisan periódicamente, con registros de quién accede y cuándo.'),
(18, 5, 'El control de acceso a activos críticos se revisa y mejora continuamente según el riesgo evaluado.'),
(19, 0, 'No existe ningún registro de ubicación para activos móviles o portátiles.'),
(19, 1, 'La ubicación se conoce de forma informal, sin registro documentado.'),
(19, 2, 'Existe un registro parcial, que no cubre todos los activos móviles.'),
(19, 3, 'Hay un registro documentado de ubicación que cubre la mayoría de los activos móviles y portátiles.'),
(19, 4, 'El registro se supervisa y actualiza periódicamente, con evidencia de verificaciones físicas.'),
(19, 5, 'El seguimiento de activos móviles se mejora continuamente, apoyado en herramientas de rastreo o gestión de dispositivos.'),
(20, 0, 'No se realizan copias de respaldo de los activos críticos.'),
(20, 1, 'Se hacen respaldos de forma manual y ocasional, sin política ni calendario.'),
(20, 2, 'Existe una política de respaldo, pero no se cumple de forma consistente ni se prueba la restauración.'),
(20, 3, 'Los respaldos se realizan según una política documentada, cubriendo la mayoría de los activos críticos.'),
(20, 4, 'Los respaldos se supervisan, se prueban periódicamente y hay evidencia de restauraciones exitosas.'),
(20, 5, 'La estrategia de respaldo se mide (tiempos de recuperación, cobertura) y mejora continuamente.'),
(21, 0, 'No se aplica ningún criterio de menor privilegio; los accesos son amplios o sin control.'),
(21, 1, 'El principio de menor privilegio se aplica de forma esporádica, según criterio individual.'),
(21, 2, 'Existe un lineamiento de menor privilegio, pero se aplica de forma inconsistente entre sistemas.'),
(21, 3, 'Los accesos se otorgan siguiendo el principio de menor privilegio en la mayoría de los sistemas.'),
(21, 4, 'La aplicación del menor privilegio se supervisa periódicamente, con evidencia de revisiones de accesos otorgados.'),
(21, 5, 'El modelo de privilegios se revisa y ajusta continuamente según el uso real y el riesgo (ej. accesos basados en roles).'),
(22, 0, 'No existe ningún procedimiento para gestionar el ciclo de vida de las cuentas de usuario.'),
(22, 1, 'Las cuentas se crean o eliminan de manera informal, sin procedimiento ni registro.'),
(22, 2, 'Existe un procedimiento esbozado, pero no se aplica de forma consistente (ej. cuentas huérfanas).'),
(22, 3, 'El ciclo de vida de las cuentas (alta, cambio, baja) sigue un procedimiento documentado en la mayoría de los casos.'),
(22, 4, 'El cumplimiento del procedimiento se supervisa, con evidencia de auditorías de cuentas activas e inactivas.'),
(22, 5, 'La gestión del ciclo de vida se mide y mejora continuamente, idealmente automatizada e integrada con RR. HH.'),
(23, 0, 'Los accesos otorgados nunca se auditan ni se revisan.'),
(23, 1, 'Se revisan accesos de forma esporádica, sin calendario definido.'),
(23, 2, 'Existe intención de revisión periódica de accesos, pero no se cumple de forma consistente.'),
(23, 3, 'Los accesos se auditan y revisan con una periodicidad definida y documentada.'),
(23, 4, 'Las revisiones de acceso se supervisan y generan evidencia formal (reportes firmados por responsables).'),
(23, 5, 'La revisión de accesos se mide y mejora continuamente, con indicadores de accesos excesivos detectados y corregidos.'),
(24, 0, 'No se exige ningún mecanismo de autenticación robusto; se usan contraseñas débiles o compartidas.'),
(24, 1, 'Se recomienda el uso de contraseñas fuertes o 2FA de manera informal, sin exigirlo.'),
(24, 2, 'Existe una política de autenticación, pero se aplica solo en algunos sistemas o de forma inconsistente.'),
(24, 3, 'Los mecanismos de autenticación adecuados (2FA, contraseñas robustas) están implementados en la mayoría de los sistemas críticos.'),
(24, 4, 'El cumplimiento de la política de autenticación se supervisa, con evidencia de auditorías de configuración.'),
(24, 5, 'Los mecanismos de autenticación se revisan y mejoran continuamente según nuevas amenazas (ej. migración a MFA moderno).'),
(25, 0, 'Las cuentas de servicio y accesos compartidos no tienen ningún control especial.'),
(25, 1, 'Se gestionan de forma informal, con credenciales compartidas sin registro.'),
(25, 2, 'Existen lineamientos para cuentas de servicio, pero se aplican de forma parcial.'),
(25, 3, 'Las cuentas de servicio y accesos compartidos se gestionan siguiendo procedimientos documentados en la mayoría de los casos.'),
(25, 4, 'La gestión de estas cuentas se supervisa periódicamente, con evidencia de revisiones y rotación de credenciales.'),
(25, 5, 'La gestión de cuentas de servicio se mide y mejora continuamente, idealmente con bóvedas de credenciales.'),
(26, 0, 'Los privilegios nunca se actualizan cuando cambian roles o personas.'),
(26, 1, 'Se ajustan de forma esporádica, cuando alguien lo solicita o lo nota.'),
(26, 2, 'Existe intención de actualizar privilegios ante cambios, pero no se cumple de forma consistente.'),
(26, 3, 'Los privilegios se revisan y actualizan siguiendo un procedimiento documentado ante la mayoría de los cambios de rol.'),
(26, 4, 'La actualización de privilegios se supervisa, con evidencia de que los cambios se reflejan oportunamente.'),
(26, 5, 'La gestión de privilegios ante cambios se mide y mejora continuamente, idealmente integrada al proceso de RR. HH.'),
(27, 0, 'No existe ningún procedimiento para aprobar o registrar privilegios elevados.'),
(27, 1, 'Los privilegios elevados se otorgan de manera informal, sin aprobación documentada.'),
(27, 2, 'Existe un procedimiento de aprobación, pero se aplica de forma inconsistente.'),
(27, 3, 'Los privilegios elevados se aprueban y registran siguiendo un procedimiento documentado en la mayoría de los casos.'),
(27, 4, 'El procedimiento se supervisa, con evidencia de aprobaciones formales para cada privilegio elevado otorgado.'),
(27, 5, 'El proceso de aprobación de privilegios elevados se mide y mejora continuamente (ej. accesos privilegiados por tiempo limitado).'),
(28, 0, 'No se monitorean las actividades de cuentas con privilegios altos.'),
(28, 1, 'El monitoreo es ocasional y manual, sin herramientas ni registro sistemático.'),
(28, 2, 'Existe algún monitoreo, pero no cubre todas las cuentas privilegiadas ni se revisa con regularidad.'),
(28, 3, 'Las actividades de cuentas privilegiadas se monitorean siguiendo un procedimiento documentado para la mayoría de los sistemas.'),
(28, 4, 'El monitoreo se supervisa activamente y genera alertas o reportes con evidencia de seguimiento.'),
(28, 5, 'El monitoreo de privilegios se mide y mejora continuamente, idealmente con analítica de comportamiento y alertas automatizadas.'),
(29, 0, 'No existen controles para prevenir el abuso de privilegios.'),
(29, 1, 'Se confía en la buena fe del personal, sin controles técnicos definidos.'),
(29, 2, 'Existen controles esbozados, pero se aplican de forma parcial o inconsistente.'),
(29, 3, 'Hay controles documentados para prevenir el abuso de privilegios, aplicados en la mayoría de los sistemas.'),
(29, 4, 'Los controles se supervisan periódicamente, con evidencia de incidentes detectados y gestionados.'),
(29, 5, 'Los controles contra el abuso de privilegios se revisan y mejoran continuamente según el riesgo observado.'),
(30, 0, 'No existe separación de funciones críticas; una sola persona puede realizar todo el proceso.'),
(30, 1, 'La separación de funciones se aplica de forma informal, dependiendo de quién esté disponible.'),
(30, 2, 'Existe un esquema de separación de funciones, pero con excepciones no controladas.'),
(30, 3, 'Las funciones críticas están separadas siguiendo un esquema documentado en la mayoría de los procesos.'),
(30, 4, 'La separación de funciones se supervisa, con evidencia de revisiones para detectar conflictos de interés.'),
(30, 5, 'El esquema de separación de funciones se revisa y mejora continuamente conforme cambia la estructura organizacional.'),
(31, 0, 'No se usan algoritmos criptográficos aprobados; se usan por defecto o sin criterio.'),
(31, 1, 'Se eligen algoritmos de forma informal, sin lineamientos de la organización.'),
(31, 2, 'Existe un lineamiento sobre algoritmos aprobados, pero se aplica de forma inconsistente.'),
(31, 3, 'Los sistemas usan algoritmos y parámetros criptográficos aprobados por la organización en la mayoría de los casos.'),
(31, 4, 'El uso de algoritmos aprobados se supervisa, con evidencia de revisiones de configuración criptográfica.'),
(31, 5, 'Los estándares criptográficos se revisan y actualizan continuamente conforme evolucionan las buenas prácticas del sector.'),
(32, 0, 'Las claves criptográficas no tienen ninguna gestión ni protección definida.'),
(32, 1, 'La gestión de claves es informal e inconsistente entre equipos o sistemas.'),
(32, 2, 'Existe algún lineamiento de gestión de claves, pero sin un proceso centralizado ni ciclo de vida definido.'),
(32, 3, 'Las claves se gestionan y protegen siguiendo un proceso documentado para la mayoría de los sistemas.'),
(32, 4, 'La gestión de claves se supervisa periódicamente, con evidencia de rotación y control de acceso a ellas.'),
(32, 5, 'Las claves se gestionan de forma centralizada con ciclo de vida completo (ej. HSM), medida y mejorada continuamente.'),
(33, 0, 'No se aplica cifrado a datos sensibles en reposo, ni siquiera cuando sería necesario.'),
(33, 1, 'El cifrado en reposo se aplica de forma puntual y a criterio individual.'),
(33, 2, 'Existe un lineamiento sobre cifrado en reposo, pero se aplica de forma parcial.'),
(33, 3, 'Los datos sensibles en reposo se cifran siguiendo un procedimiento documentado en la mayoría de los sistemas.'),
(33, 4, 'La aplicación del cifrado se supervisa, con evidencia de verificaciones sobre qué datos están cifrados.'),
(33, 5, 'La protección de datos en reposo se revisa y mejora continuamente según la clasificación de la información.'),
(34, 0, 'La información confidencial en los backups no se protege con criptografía.'),
(34, 1, 'Algunos backups se cifran de forma puntual, sin criterio uniforme.'),
(34, 2, 'Existe un lineamiento de cifrado de backups, pero se aplica de forma inconsistente.'),
(34, 3, 'Los backups con información confidencial se cifran siguiendo un procedimiento documentado en la mayoría de los casos.'),
(34, 4, 'El cifrado de backups se supervisa periódicamente, con evidencia de verificación.'),
(34, 5, 'La protección criptográfica de los backups se mide y mejora continuamente, integrada a la política de respaldo.'),
(35, 0, 'Las políticas de uso de criptografía nunca se revisan.'),
(35, 1, 'Se revisan de forma esporádica, sin calendario definido.'),
(35, 2, 'Existe intención de revisión periódica, pero no se cumple de forma consistente.'),
(35, 3, 'Las políticas de criptografía se revisan con una periodicidad definida y documentada.'),
(35, 4, 'Las revisiones se supervisan y quedan evidencias formales de cada actualización.'),
(35, 5, 'Las políticas de criptografía se revisan y mejoran de forma continua conforme evolucionan los estándares del sector.'),
(36, 0, 'Los canales que transportan información sensible no se cifran ni se aseguran.'),
(36, 1, 'El cifrado de canales se aplica de forma puntual, sin criterio definido.'),
(36, 2, 'Existe un lineamiento de cifrado de comunicaciones, pero se aplica de forma inconsistente.'),
(36, 3, 'Los canales que transportan información sensible se cifran o aseguran siguiendo un procedimiento documentado.'),
(36, 4, 'La aplicación del cifrado en comunicaciones se supervisa, con evidencia de verificaciones periódicas.'),
(36, 5, 'La seguridad de las comunicaciones se mide y mejora continuamente conforme evolucionan las amenazas.'),
(37, 0, 'No se usan VPN ni canales seguros para accesos remotos.'),
(37, 1, 'Se usan canales seguros de forma ocasional, según criterio individual.'),
(37, 2, 'Existe un lineamiento de acceso remoto seguro, pero se aplica de forma inconsistente.'),
(37, 3, 'Los accesos remotos se realizan mediante VPN o canales seguros siguiendo un procedimiento documentado.'),
(37, 4, 'El uso de canales seguros se supervisa, con evidencia de auditorías de accesos remotos.'),
(37, 5, 'El acceso remoto seguro se mide y mejora continuamente (ej. zero trust, monitoreo continuo de sesiones).'),
(38, 0, 'No se controlan ni registran las conexiones entrantes y salientes críticas.'),
(38, 1, 'El control de conexiones es informal, sin registro sistemático.'),
(38, 2, 'Existen controles básicos (ej. firewall), pero sin revisión periódica de los registros.'),
(38, 3, 'Las conexiones críticas se controlan y registran siguiendo un procedimiento documentado en la mayoría de los casos.'),
(38, 4, 'El control de conexiones se supervisa activamente, con evidencia de revisión de bitácoras y alertas.'),
(38, 5, 'El monitoreo de conexiones se mide y mejora continuamente, con analítica y respuesta automatizada ante anomalías.'),
(39, 0, 'No existen políticas para el uso seguro de correo o transferencia de archivos.'),
(39, 1, 'Se dan recomendaciones informales sobre correo o transferencia de archivos, sin política formal.'),
(39, 2, 'Existe una política, pero se aplica de forma parcial o desconocida por el personal.'),
(39, 3, 'Hay políticas documentadas para uso seguro de correo y transferencia de archivos, aplicadas en la mayoría de los casos.'),
(39, 4, 'El cumplimiento de estas políticas se supervisa, con evidencia de controles técnicos (ej. filtros, DLP).'),
(39, 5, 'Las políticas de uso seguro se revisan y mejoran continuamente según incidentes o nuevas amenazas detectadas.'),
(40, 0, 'No se gestionan acuerdos de seguridad con proveedores de servicios de comunicaciones.'),
(40, 1, 'Se confía en el proveedor sin ningún acuerdo de seguridad específico.'),
(40, 2, 'Existen acuerdos generales, pero sin cláusulas de seguridad específicas ni seguimiento.'),
(40, 3, 'Los acuerdos con proveedores de comunicaciones incluyen cláusulas de seguridad documentadas.'),
(40, 4, 'El cumplimiento de los acuerdos se supervisa periódicamente, con evidencia de revisiones al proveedor.'),
(40, 5, 'La gestión de proveedores de comunicaciones se mide y mejora continuamente según el riesgo asociado.'),
(41, 0, 'No existen procedimientos operativos documentados.'),
(41, 1, 'Los procedimientos existen solo en el conocimiento informal del personal.'),
(41, 2, 'Existen algunos procedimientos documentados, pero desactualizados o poco conocidos.'),
(41, 3, 'Los procedimientos operativos están documentados, actualizados y son conocidos por la mayoría del personal involucrado.'),
(41, 4, 'El cumplimiento de los procedimientos se supervisa, con evidencia de auditorías o revisiones internas.'),
(41, 5, 'Los procedimientos operativos se revisan y mejoran de forma continua según el desempeño observado.'),
(42, 0, 'No existe ningún control para cambios en producción.'),
(42, 1, 'Los cambios se realizan de forma ad hoc, sin aprobación ni registro.'),
(42, 2, 'Existe un proceso de change management esbozado, pero no se sigue de forma consistente.'),
(42, 3, 'Los cambios en producción siguen un proceso documentado de solicitud, prueba y aprobación en la mayoría de los casos.'),
(42, 4, 'El proceso de cambios se supervisa, con evidencia de aprobaciones y pruebas antes del despliegue.'),
(42, 5, 'La gestión de cambios se mide y mejora continuamente (ej. tasa de cambios fallidos, tiempo de despliegue).'),
(43, 0, 'No se realiza ningún monitoreo ni registro de eventos operativos.'),
(43, 1, 'El monitoreo es manual y ocasional, sin herramientas dedicadas.'),
(43, 2, 'Existe monitoreo parcial, que no cubre todos los sistemas relevantes.'),
(43, 3, 'Los eventos operativos relevantes se monitorean y registran siguiendo un procedimiento documentado.'),
(43, 4, 'El monitoreo se supervisa activamente, generando alertas y reportes con evidencia de seguimiento.'),
(43, 5, 'El monitoreo de eventos se mide y mejora continuamente, idealmente con correlación automatizada de eventos (SIEM).'),
(44, 0, 'No se gestionan parches ni vulnerabilidades en los sistemas críticos.'),
(44, 1, 'Los parches se aplican de forma esporádica, sin calendario ni evaluación de vulnerabilidades.'),
(44, 2, 'Existe un proceso de gestión de parches, pero no se cumple de forma consistente en todos los sistemas.'),
(44, 3, 'Los parches y vulnerabilidades se gestionan siguiendo un procedimiento documentado para la mayoría de los sistemas críticos.'),
(44, 4, 'La gestión de parches se supervisa, con evidencia de escaneos de vulnerabilidades y tiempos de remediación.'),
(44, 5, 'La gestión de vulnerabilidades se mide y mejora continuamente, con métricas de tiempo de exposición y remediación.'),
(45, 0, 'No se realizan revisiones de configuración ni de seguridad.'),
(45, 1, 'Las revisiones son esporádicas y sin criterio definido.'),
(45, 2, 'Existe intención de revisar configuraciones periódicamente, pero no se cumple de forma consistente.'),
(45, 3, 'Las revisiones de configuración y seguridad se realizan con una periodicidad definida y documentada.'),
(45, 4, 'Las revisiones se supervisan activamente y generan evidencia formal de hallazgos y correcciones.'),
(45, 5, 'Las revisiones de configuración se miden y mejoran continuamente, idealmente con verificación automatizada de líneas base.'),
(46, 0, 'No existe ningún proceso para gestionar incidentes de seguridad; la respuesta es reactiva y no planificada.'),
(46, 1, 'Los incidentes se atienden de manera informal, según quien esté disponible en el momento.'),
(46, 2, 'Existe un proceso esbozado de gestión de incidentes, pero no se aplica de forma consistente.'),
(46, 3, 'Hay un proceso formal de gestión de incidentes, documentado y aplicado en la mayoría de los casos.'),
(46, 4, 'El proceso se supervisa activamente, con monitoreo y evidencia de tiempos de respuesta medidos.'),
(46, 5, 'La gestión de incidentes está automatizada y en mejora continua, con capacidades predictivas y de respuesta orquestada.'),
(47, 0, 'Los incidentes no se registran ni se clasifican de ninguna forma.'),
(47, 1, 'Se anotan de manera informal (correo, chat), sin clasificación ni seguimiento estructurado.'),
(47, 2, 'Existe un registro de incidentes, pero incompleto o sin clasificación consistente.'),
(47, 3, 'Los incidentes se registran, clasifican y se les da seguimiento siguiendo un procedimiento documentado.'),
(47, 4, 'El registro y clasificación se supervisan, con evidencia de reportes periódicos de estado.'),
(47, 5, 'El registro de incidentes se mide y mejora continuamente, con métricas de tiempo de detección, respuesta y cierre.'),
(48, 0, 'No se realizan pruebas ni ejercicios de respuesta a incidentes.'),
(48, 1, 'Se han hecho pruebas puntuales, sin planificación ni periodicidad.'),
(48, 2, 'Existe intención de realizar ejercicios periódicos, pero no se cumple de forma consistente.'),
(48, 3, 'Se realizan pruebas o simulacros de respuesta a incidentes con una periodicidad definida y documentada.'),
(48, 4, 'Los ejercicios se supervisan y generan evidencia de lecciones aprendidas incorporadas al plan.'),
(48, 5, 'Los ejercicios de respuesta se miden y mejoran continuamente, escalando en complejidad y realismo con el tiempo.'),
(49, 0, 'No existen canales definidos para reportar incidentes de seguridad.'),
(49, 1, 'Los incidentes se reportan de manera informal, a quien se tenga a mano.'),
(49, 2, 'Existe un canal de reporte, pero es poco conocido o usado de forma inconsistente.'),
(49, 3, 'Hay canales formales y conocidos para reportar incidentes, usados en la mayoría de los casos.'),
(49, 4, 'El uso de los canales se supervisa, con evidencia de trazabilidad de reportes recibidos y atendidos.'),
(49, 5, 'Los canales de reporte se miden y mejoran continuamente (ej. tiempos de respuesta, satisfacción de quien reporta).'),
(50, 0, 'No hay ninguna retroalimentación a la organización tras los incidentes.'),
(50, 1, 'Se comentan lecciones aprendidas de manera informal, entre pocas personas.'),
(50, 2, 'Existen informes posteriores a incidentes, pero no se comunican ni aplican de forma consistente.'),
(50, 3, 'Se documentan lecciones aprendidas y se comunican a las áreas relevantes tras la mayoría de los incidentes.'),
(50, 4, 'La aplicación de lecciones aprendidas se supervisa, con evidencia de mejoras implementadas a partir de ellas.'),
(50, 5, 'La retroalimentación post-incidente alimenta un ciclo de mejora continua medido (reducción de incidentes recurrentes).'),
(51, 0, 'No existe ningún control de acceso físico a instalaciones críticas.'),
(51, 1, 'Hay controles básicos e informales (ej. una llave compartida), sin autorización formal.'),
(51, 2, 'Existe un control de acceso físico, pero sin autorización formal documentada ni registro consistente.'),
(51, 3, 'El acceso a instalaciones críticas requiere autorización formal documentada, siguiendo el procedimiento en la mayoría de los casos.'),
(51, 4, 'El acceso físico se supervisa, con revisión periódica (ej. trimestral) de quién tiene acceso autorizado.'),
(51, 5, 'El control de acceso físico se mide y mejora continuamente, integrado a sistemas de control electrónico y auditoría.'),
(52, 0, 'No existen medidas de protección física para equipos ni servidores.'),
(52, 1, 'Hay medidas mínimas e informales (ej. puerta con llave), sin criterio definido.'),
(52, 2, 'Existen medidas de protección, pero incompletas o aplicadas de forma inconsistente.'),
(52, 3, 'Los equipos y servidores cuentan con medidas de protección física documentadas, aplicadas en la mayoría de los casos.'),
(52, 4, 'Las medidas de protección se supervisan periódicamente, con evidencia de inspecciones.'),
(52, 5, 'La protección física de equipos se revisa y mejora continuamente según amenazas o incidentes detectados.'),
(53, 0, 'No se gestionan visitantes ni accesos temporales de ninguna forma.'),
(53, 1, 'Los visitantes ingresan sin registro ni acompañamiento formal.'),
(53, 2, 'Existe un registro de visitantes, pero incompleto o sin control de acompañamiento.'),
(53, 3, 'Los visitantes y accesos temporales se gestionan siguiendo un procedimiento documentado (registro, acompañamiento, gafete).'),
(53, 4, 'La gestión de visitantes se supervisa, con evidencia de registros revisados periódicamente.'),
(53, 5, 'La gestión de visitantes se mide y mejora continuamente, idealmente con control electrónico de accesos temporales.'),
(54, 0, 'No se realiza ninguna inspección ni mantenimiento de los controles físicos.'),
(54, 1, 'Las inspecciones se hacen de forma esporádica, solo cuando algo falla.'),
(54, 2, 'Existe intención de inspeccionar periódicamente, pero no se cumple de forma consistente.'),
(54, 3, 'Los controles físicos se inspeccionan y mantienen con una periodicidad definida y documentada.'),
(54, 4, 'Las inspecciones se supervisan activamente, con evidencia formal de cada mantenimiento realizado.'),
(54, 5, 'El mantenimiento de controles físicos se mide y mejora continuamente según el historial de fallas.'),
(55, 0, 'No existen controles de redundancia ni recuperación física para equipos críticos.'),
(55, 1, 'Hay alguna medida de respaldo física (ej. UPS básico), sin plan formal.'),
(55, 2, 'Existen medidas de redundancia parciales, no documentadas ni probadas.'),
(55, 3, 'Los equipos críticos cuentan con controles de redundancia y recuperación física documentados.'),
(55, 4, 'La redundancia se supervisa y se prueba periódicamente, con evidencia de los resultados.'),
(55, 5, 'Los controles de redundancia física se miden y mejoran continuamente, integrados al plan de continuidad del negocio.'),
(56, 0, 'No se adoptan medidas ambientales (temperatura, humedad) para proteger los activos.'),
(56, 1, 'Hay medidas informales y puntuales (ej. un ventilador), sin monitoreo.'),
(56, 2, 'Existen medidas ambientales básicas, pero sin monitoreo ni umbrales definidos.'),
(56, 3, 'Se aplican medidas ambientales documentadas, con umbrales de temperatura/humedad definidos y monitoreados.'),
(56, 4, 'Las condiciones ambientales se supervisan activamente, con alertas y evidencia de seguimiento.'),
(56, 5, 'El control ambiental se mide y mejora continuamente, integrado a sistemas de monitoreo automatizado.'),
(57, 0, 'No existen sistemas contra incendios ni de detección adecuados.'),
(57, 1, 'Hay extintores básicos, sin sistema de detección ni mantenimiento programado.'),
(57, 2, 'Existen sistemas de detección/incendio, pero no se revisan ni prueban con regularidad.'),
(57, 3, 'Se cuenta con sistemas contra incendios y detección documentados, con mantenimiento periódico.'),
(57, 4, 'Los sistemas se supervisan activamente, con evidencia de pruebas y certificaciones vigentes.'),
(57, 5, 'La protección contra incendios se mide y mejora continuamente, alineada a estándares de la industria.'),
(58, 0, 'No se protege la infraestructura eléctrica ni los suministros críticos.'),
(58, 1, 'Hay protección eléctrica básica (ej. regulador), sin redundancia ni plan.'),
(58, 2, 'Existen medidas de protección eléctrica, pero sin redundancia completa ni pruebas periódicas.'),
(58, 3, 'La infraestructura eléctrica cuenta con protección documentada (UPS, planta eléctrica) para los suministros críticos.'),
(58, 4, 'La protección eléctrica se supervisa periódicamente, con evidencia de pruebas de los sistemas de respaldo.'),
(58, 5, 'La infraestructura eléctrica se mide y mejora continuamente, con monitoreo en tiempo real de su disponibilidad.'),
(59, 0, 'No se realizan evaluaciones de riesgo físico ni ambiental.'),
(59, 1, 'Se identifican riesgos de forma informal, sin evaluación documentada.'),
(59, 2, 'Existe intención de evaluar riesgos físicos/ambientales periódicamente, pero no se cumple de forma consistente.'),
(59, 3, 'Las evaluaciones de riesgo físico y ambiental se realizan con una periodicidad definida y documentada.'),
(59, 4, 'Las evaluaciones se supervisan activamente, con evidencia formal de hallazgos y planes de acción.'),
(59, 5, 'Las evaluaciones de riesgo físico/ambiental se miden y mejoran continuamente, integradas a la gestión de riesgos general.'),
(60, 0, 'No existen planes de contingencia ante fallas ambientales.'),
(60, 1, 'Hay respuestas improvisadas ante fallas ambientales, sin plan documentado.'),
(60, 2, 'Existe un plan esbozado, pero no probado ni actualizado.'),
(60, 3, 'Hay planes de contingencia documentados ante fallas ambientales, conocidos por el personal responsable.'),
(60, 4, 'Los planes se supervisan y prueban periódicamente, con evidencia de los resultados de las pruebas.'),
(60, 5, 'Los planes de contingencia ambiental se miden y mejoran continuamente tras cada prueba o evento real.'),
(61, 0, 'No se realiza ninguna identificación ni evaluación de riesgos.'),
(61, 1, 'Los riesgos se identifican de manera informal y ocasional.'),
(61, 2, 'Existe un proceso de identificación de riesgos, pero no se aplica de forma periódica ni consistente.'),
(61, 3, 'Se realiza identificación y evaluación de riesgos con una periodicidad definida, siguiendo un proceso documentado (ej. ciclo PDCA).'),
(61, 4, 'El proceso de evaluación de riesgos se supervisa, con evidencia formal de cada ciclo realizado.'),
(61, 5, 'La identificación y evaluación de riesgos se mide y mejora continuamente, integrada a la gestión estratégica.'),
(62, 0, 'No se documentan tratamientos ni planes de mitigación de riesgos.'),
(62, 1, 'Se atienden riesgos de forma reactiva, sin plan documentado.'),
(62, 2, 'Existen algunos planes de tratamiento, pero incompletos o sin seguimiento.'),
(62, 3, 'Los tratamientos y planes de mitigación de riesgos están documentados y se aplican en la mayoría de los casos.'),
(62, 4, 'La ejecución de los planes se supervisa, con evidencia del avance de cada medida de mitigación.'),
(62, 5, 'Los planes de tratamiento se miden y mejoran continuamente según su efectividad real en reducir el riesgo.'),
(63, 0, 'Los riesgos no se priorizan de ninguna forma.'),
(63, 1, 'La priorización es informal, basada en percepción individual.'),
(63, 2, 'Existe un criterio de priorización esbozado (impacto/probabilidad), pero se aplica de forma inconsistente.'),
(63, 3, 'Los riesgos se priorizan según impacto y probabilidad siguiendo una metodología documentada.'),
(63, 4, 'La priorización se supervisa periódicamente, con evidencia de matrices de riesgo actualizadas.'),
(63, 5, 'La metodología de priorización se revisa y mejora continuamente según la experiencia y nuevos escenarios de riesgo.'),
(64, 0, 'Los riesgos nunca se revisan tras cambios significativos en la organización.'),
(64, 1, 'Se revisan de forma esporádica, solo si alguien lo recuerda.'),
(64, 2, 'Existe intención de revisar riesgos tras cambios, pero no se cumple de forma consistente.'),
(64, 3, 'Los riesgos se revisan siguiendo un procedimiento documentado cada vez que ocurre un cambio significativo.'),
(64, 4, 'Estas revisiones se supervisan, con evidencia formal de que se realizaron tras cada cambio relevante.'),
(64, 5, 'La revisión de riesgos ante cambios se mide y mejora continuamente, integrada a la gestión del cambio organizacional.'),
(65, 0, 'Los riesgos no se comunican a la alta dirección ni a partes interesadas.'),
(65, 1, 'Se mencionan riesgos de forma informal en conversaciones puntuales.'),
(65, 2, 'Existe algún reporte de riesgos, pero no llega de forma consistente a la alta dirección.'),
(65, 3, 'Los riesgos se comunican formalmente a la alta dirección y partes interesadas con una periodicidad definida.'),
(65, 4, 'La comunicación de riesgos se supervisa, con evidencia de actas o reportes revisados por la dirección.'),
(65, 5, 'La comunicación de riesgos se mide y mejora continuamente, con retroalimentación de la dirección incorporada al proceso.'),
(66, 0, 'No se identifican los requisitos legales o regulatorios aplicables a la organización.'),
(66, 1, 'Se conocen algunos requisitos de forma informal, sin documentarlos.'),
(66, 2, 'Existe una identificación parcial de requisitos legales, incompleta o desactualizada.'),
(66, 3, 'Los requisitos legales y regulatorios aplicables están identificados y documentados de forma actualizada.'),
(66, 4, 'La identificación de requisitos se supervisa periódicamente, con evidencia de revisiones legales.'),
(66, 5, 'La identificación de requisitos legales se mide y mejora continuamente, con vigilancia activa de cambios normativos.'),
(67, 0, 'No se gestionan contratos ni obligaciones de seguridad con proveedores.'),
(67, 1, 'Se mencionan obligaciones de forma verbal, sin cláusulas contractuales.'),
(67, 2, 'Existen cláusulas de seguridad en algunos contratos, sin revisión sistemática.'),
(67, 3, 'Los contratos con proveedores incluyen cláusulas de seguridad documentadas en la mayoría de los casos.'),
(67, 4, 'El cumplimiento de las obligaciones contractuales se supervisa, con evidencia de revisiones periódicas.'),
(67, 5, 'La gestión contractual de proveedores se mide y mejora continuamente según el riesgo legal asociado.'),
(68, 0, 'No se mantiene ninguna evidencia de cumplimiento ni registros necesarios.'),
(68, 1, 'Se guardan algunos documentos de forma desorganizada, sin criterio de retención.'),
(68, 2, 'Existe un archivo de evidencias, pero incompleto respecto a lo requerido.'),
(68, 3, 'Se mantiene evidencia de cumplimiento y registros necesarios de forma organizada para la mayoría de los requisitos.'),
(68, 4, 'La gestión de evidencias se supervisa, con revisiones periódicas de completitud y vigencia.'),
(68, 5, 'La gestión de evidencias de cumplimiento se mide y mejora continuamente, con repositorios auditables y trazables.'),
(69, 0, 'No se realizan auditorías para verificar el cumplimiento legal.'),
(69, 1, 'Se hacen revisiones informales y ocasionales, sin metodología definida.'),
(69, 2, 'Existe intención de auditar el cumplimiento legal, pero no se cumple de forma consistente.'),
(69, 3, 'Se realizan auditorías de cumplimiento legal con una periodicidad definida y documentada.'),
(69, 4, 'Las auditorías se supervisan, con evidencia formal de hallazgos y planes de corrección.'),
(69, 5, 'Las auditorías de cumplimiento legal se miden y mejoran continuamente, con seguimiento de la resolución de hallazgos.'),
(70, 0, 'No se evalúa el impacto de cambios regulatorios en la organización.'),
(70, 1, 'El impacto se analiza de forma informal cuando alguien se entera de un cambio.'),
(70, 2, 'Existe algún proceso de evaluación, pero no se aplica de forma sistemática a todos los cambios.'),
(70, 3, 'El impacto de los cambios regulatorios se evalúa siguiendo un procedimiento documentado en la mayoría de los casos.'),
(70, 4, 'La evaluación de impacto se supervisa, con evidencia de planes de adecuación ante cada cambio relevante.'),
(70, 5, 'La evaluación de impacto regulatorio se mide y mejora continuamente, con vigilancia proactiva de cambios normativos.'),
(71, 0, 'No se realizan auditorías internas de seguridad de la información.'),
(71, 1, 'Se hacen revisiones informales y ocasionales, sin metodología ni calendario.'),
(71, 2, 'Existe intención de auditar periódicamente, pero no se cumple de forma consistente.'),
(71, 3, 'Se realizan auditorías internas de seguridad con una periodicidad definida y documentada.'),
(71, 4, 'Las auditorías se supervisan activamente, con evidencia formal de su ejecución y alcance.'),
(71, 5, 'El programa de auditoría interna se mide y mejora continuamente, ampliando su alcance según el riesgo.'),
(72, 0, 'Los hallazgos de auditoría no se documentan ni se les da seguimiento.'),
(72, 1, 'Se anotan hallazgos de forma informal, sin plan de acción.'),
(72, 2, 'Existen hallazgos documentados, pero el seguimiento de las acciones correctivas es incompleto.'),
(72, 3, 'Los hallazgos y sus acciones correctivas se documentan y se les da seguimiento siguiendo un procedimiento definido.'),
(72, 4, 'El seguimiento de acciones correctivas se supervisa, con evidencia del estado de cada hallazgo.'),
(72, 5, 'El seguimiento de hallazgos se mide y mejora continuamente, con indicadores de tiempo de cierre y recurrencia.'),
(73, 0, 'Los controles y resultados de auditoría nunca se revisan con la dirección.'),
(73, 1, 'Se comentan resultados de forma informal, sin reunión ni acta.'),
(73, 2, 'Existen reuniones de revisión, pero sin periodicidad definida ni actas formales.'),
(73, 3, 'Los controles y resultados de auditoría se revisan con la dirección siguiendo una periodicidad definida.'),
(73, 4, 'Estas revisiones se supervisan y quedan formalmente documentadas (actas, acuerdos, responsables).'),
(73, 5, 'La revisión con la dirección se mide y mejora continuamente, integrada a la toma de decisiones estratégicas.'),
(74, 0, 'No se mantienen registros de auditoría ni evidencias suficientes.'),
(74, 1, 'Se guardan algunos registros de forma desorganizada, sin criterio de retención.'),
(74, 2, 'Existen registros de auditoría, pero incompletos o de difícil acceso.'),
(74, 3, 'Se mantienen registros de auditoría y evidencias suficientes de forma organizada para la mayoría de los ciclos.'),
(74, 4, 'La gestión de registros se supervisa, con revisiones periódicas de completitud y trazabilidad.'),
(74, 5, 'La gestión de registros de auditoría se mide y mejora continuamente, con repositorios auditables a largo plazo.'),
(75, 0, 'No se evalúa la eficacia de las acciones tomadas tras las auditorías.'),
(75, 1, 'Se asume informalmente que las acciones funcionaron, sin verificación.'),
(75, 2, 'Existe intención de evaluar la eficacia, pero no se hace de forma consistente.'),
(75, 3, 'La eficacia de las acciones correctivas se evalúa siguiendo un procedimiento documentado en la mayoría de los casos.'),
(75, 4, 'La evaluación de eficacia se supervisa, con evidencia formal de los resultados obtenidos.'),
(75, 5, 'La eficacia de las acciones se mide y mejora continuamente, retroalimentando el ciclo de auditoría y gestión de riesgos.');
